### ISSUE TITLE
Sprint 1 Review and Demo

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27294-IntoTheDeep#10]

**Comment by Walker21122008** [comment]
Kailyn & Hasini
(https://docs.google.com/document/d/1bYqit956OKTgbPXT8INHdXmDjYpi8g9jWEm6jHD3104/edit?usp=sharing)

**Comment by Aletrioli** [comment]
Successes, failures, and next steps:

Successes:
- The starter robot intake was build completely
- The design is able to reliably take in and spit out samples

Failures:
- The wheels were placed incorrectly, and consequently do not touch the floor, leaving the extrusions to drag along the floor
- Very unstable when attached to the slider
- The hex shaft extends far beyond the length of the intake

Next steps:
- Create a custom-ramp to replace the corrugated plastic
- Cut the hex shaft
- Move the wheels so they hold up the intake
- Look into shaving off some weight (possibly by replacing some extrusions with lighter, plastic printed pieces)

**Comment by riochan26** [comment]
Successes:
* System was successfully brainstormed
* Motors are working as intended

Failures:
* The chain was extremely annoying to manipulate and use, leading to failure

Next Steps:
* Finish the chain and ensure it functions properly with the wheel systems
* Assemble the rest of the frame and ensure it is able to move freely and withstand the weight of the other systems
* Link up power to the motors and code the wheels to move properly according to gamepad input
