### ISSUE TITLE
Sprint 2 Review and Demo

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27294-IntoTheDeep#16]

**Comment by Walker21122008** [comment]
[Uploading Hasini & Kailyn - Sprint 2_ Reaching for the High_Low Basket (1).docx…]()

**Comment by Walker21122008** [comment]
[https://docs.google.com/document/d/1Rp3MuxtzS-E2kpX_Z_wKBnIBBkfcfQmH2LR4hlytWuE/edit?tab=t.0](url)

**Comment by Walker21122008** [comment]
[Hasini & Kailyn - Sprint 2_ Reaching for the High_Low Basket (1).docx](https://github.com/user-attachments/files/17528710/Hasini.Kailyn.-.Sprint.2_.Reaching.for.the.High_Low.Basket.1.docx)

**Comment by Aletrioli** [comment]
Successes, failures, and next steps:

Successes:
- The tower was completed and attached to the drive-train

Failures:
- I did not sketch out or plan designs for my intake as I spent more time than I would have thought assembling and incorporating the tower

Next steps:
- Sketch and then create a custom-ramp to replace the corrugated plastic
- Adjust the intake as necessary to function with the sliders
- Fully assemble the robot

**Comment by riochan26** [comment]
Successes, Failures and Next Steps

Success:
Drivetrain is built without motors being hooked up
Integrated the Shoulder of the Arm into the the drivetrain

Failures:
None

Next Steps:
Code the drivetrain
Hook up motors into the DriverHub
